Excel табличка с предположительной архитектурой БД
gri-gri/itmo_lab_delivery_application pull request #31
Opened 2021-11-07 10:57 UTC by dobrmar

1. Табличка "Студенты в группах": нормально ли наличие UK1 и UK2 (id и табельный номер) или лучше декомпозировать на две таблички name-number и id-number?
2. Табличка "Лабосдача": если лабосдача еще не проверена, в mark какое-то дефолтное значение (-1)? Или опять-таки декомпозировать и добавить табличку del_lab_id-mark?
3. Табличка "Преподаватели": т.к. не у всех есть табельные номера, мы надеемся, что у всех преподов уникальные ФИО? Если да, надо добавить UK2 в name?

2021-11-07 14:46 UTC, gri-gri commented
1. Можно просто убрать, что табельный номер - уникальный ключ. Как думаешь?
2. Не, не думаю, что здесь нужно декомпозировать. Можно действительно просто -1 ставить.
3. Можно им добавить табельный номер (не у всех он есть, но у многих, остальным - какое-нибудь дефолтное -1), и вместе с ФИО сделать уникальным. Про остальных - да, молимся.

2021-11-07 14:49 UTC, gri-gri requested changes
1. Табличка "Группо-дисциплины". disc_id должно быть FK2, а не FK1
2. Табличка "Препод Группо-дисциплина". group_disc_id должно быть FK2, а не Fk2 (минорно).

2021-11-10 06:07 UTC, gri-gri commented
Да, кстати, мне кажется для таких коммитов было бы удобно добавлять поясняющий .md-файл, в который бы подгружался скриншот, а то скачивать и открывать тяжело. Но excel всё равно нужен, чтобы можно было легко править.

2021-11-10 06:36 UTC, gri-gri commented
Слушай, мне кажется, в табличке "Лаба Группо-дисциплина" надо изменить is_opened на was_opened, чтобы не возникало коллизий между "было ли открыто" и "открыто ли сейчас". И надо добавить туда поле хард дедлайна. В общем, надо подумать и эти 2 пункта как-то сделать.

2021-11-11 00:23 UTC, dobrmar commented
requested changes + :
"Дисциплины" и "Группы": + UK2
"Преподаватели": + number_ISU и UK2
"Лабосдача": + date - дата сдачи лабы. Сначала хотела сделать что-то вроде "is_before_deadline", но т.к. дедлайн привязан к ГП, а лабосдача - к лабе, решила, что лучше просто дату сдачи запоминать и проверять уже после.
"Лаба ГП": is_opened -> is_available, + deadline.

2021-11-11 08:17 UTC, gri-gri approved these changes
Супер.

2021-11-11 08:17 UTC, merged