Databasereader
gri-gri/itmo_lab_delivery_application pull request #53
Opened 2021-11-21 04:39 UTC by dobrmar

класс databasereader.
Ничего не тестила еще, так что вероятность багов большая. 
Пока отсутствуют методы редактирования лабы (uc 4) и просмотра студентом своих лабосдач по группе (?) (uc 9).

2021-11-21 04:47 UTC, dobrmar commented
Из описания uc 8 и uc 9:

> 1. Пользователь выбирает из выпадающего списка из групп, в которых он состоит.
> 2. Выбирает из списка работ нужную 

Не лучше ли сделать выбор не по группе, а по дисциплине?

2021-11-23 13:20 UTC, gri-gri commented
Это вопрос фронту, переправь это им.

2021-11-23 14:39 UTC, gri-gri commented
Смотри, я сейчас много чего тут накатаю. Практически всё минорно. Я просто высказываю своё мнение, может это обсудить, ты сможешь это исправлять или нет. Просто напиши, чтобы я понимал, что надо это заапрувить или подождать, пока ты исправишь.
__NB! Как нам организовать тестирование этого дела?__

1. Комментарии на русском, конечно, помогают, но не всегда. Не всегда понятно, что конкретно делает метод (например, teacher_to_gd) или что обозначает переменная (прямая стрельба себе в ногу: в teacher_to_labs переменная "эль", "ай", или "один"). Лучше придерживаться одного стиля в названиях методов класса. Например, начинать с повелительного глагола: get_ids_of_group_disciplines_of_teacher (кроме what_is_lab, конечно, это может стать замечательным исключением).
2. Уважуха за use_cases.md
3. Очень часто встречаются магические числа, в основном в индексах. Можно было бы, наверное, это сделать в формате словарей (если это был бы финальный вариант, но и в черновых негоже нечистый код писать).
4. Не очень понятно, какие "настройки" должны быть в аргументе функции new_lab
4. В функции add_gd_to_lab (хотя лучше attach тут использовать) тоже очень странный аргумент gd_status_deadline.
5. Тупил из-за коллизии сокращений: delivery лучше сокращать до deliv, а не до del - удаление.
6. Не понимаю, почему в main.py/delete_lab в одном цикле обход в прямом порядке, а в трёх - в обратном.
7. В main.py/teacher_to_del_labs можно обойтись без вложенного цикла за счёт промежуточных списков или множеств, как ты сделала в остальных местах.
8. А почему в use_cases.md стоят грустные смайлики? Ты же уже реализовала все те функции, которые нужны для этих uc.

2021-11-23 14:39 UTC, gri-gri requested changes
Кроме моего того комментария, есть менее минорные вещи. Главная - __переменные с таблицами данных не будут меняться!__ Они же глобальные, ты их просто импортируешь из другого файла (в таком случае, их обычно пишут заглавными буквами, кстати). Может быть, стоило это сделать в качестве полей класса.
1. В base.py в group_disc должно быть group_id, а не group_dics.
2. В main.py функция teacher_to_labs. Странная строка 37, проверка во втором цикле. Плюс, мне кажется, должны передаваться не только свойства лабы, но и свойство лабы для каждой групподисциплины (чтобы оно во фронте высвечивалось, для кого открыто, закрыто и так далее). Плюс где используется what_is_lab?
3. Почему в main.py/delete_lab не стоит break во втором цикле?

2021-11-23 15:46 UTC, dobrmar commented
1. Сделаю
2. ty
3. Не очень понимаю, что ты имеешь в виду. На данный момент прога исходит из того, что значения id в каждой табличке - любые числа, идущие в порядке возрастания. Id нового значения в табличке = id последней строки + 1
4. list_of_gfs_with_settings - двумерный массив с id ГД, статусами (доступно/недоступно) и дедлайнами. Возможно, стоит это убрать и из основной программы при создании вызывать отдельно new_lab и add_gd_to_lab вместо вызова второй из вызова первой.
5. Массив ГД id, статус (доступно/недоступно), дедлайн.
6. Окей
7. Если мы будем удалять элементы из массива во время его обхода с начала, у нас получатся беды с индексами. Если обходить с конца - всё норм, т.к. индексы меняются только для тех элементов, которые мы уже проверили (кажется). В первом цикле нам надо удалить ровно один элемент, а потом брейкнуть, поэтому без разницы, с какой стороны идти.
8. Окей
9. Эмм, нет? Редактирование лабы на данный момент можно сделать только путем удалить лабу - добавить лабу, не уверена, что это наилучший вариант. Для 9 uc пока тоже ничего нет (кроме del_lab - просмотр лабосдачы по id). Сложность в выводе списка лабосдач: если мы это делаем без сортировки по группе/дисциплине, то всё легко - просто пробегаемся по табличке лабосдач, там же хранится id студента. Но если пользователь сначала выбирает, по какому критерию ему лабосдачи показываются (как написано в uc), надо уже забегать в другие таблички. Я это доделаю, но желательно решить вот это 

> Из описания uc 8 и uc 9:
> 
> > 1. Пользователь выбирает из выпадающего списка из групп, в которых он состоит.
> > 2. Выбирает из списка работ нужную
> 
> Не лучше ли сделать выбор не по группе, а по дисциплине?

2021-11-23 15:49 UTC, dobrmar commented
Тестирование предлагаю в начале следующего спринта сделать.

2021-11-23 16:25 UTC, dobrmar commented
1. Я немного туплю с 
 > переменные с таблицами данных не будут меняться 

На время одного запуска программы они меняются, а большее в текущем варианте и не надо? По поводу полей класса согласна, стоит сделать это хотя бы ради того, чтобы ide перестала ругаться с "method may be static". Другой вопрос, что когда мы заменим двумерные списки на нормальные бд, у нас класс опять останется без полей. Не лучше ли тогда в финальной версии удалить класс и просто оставить все его методы как функции в отдельном файле? 
2. Упс, исправлю. what_is_lab - возвращение инфы по лабе по id. Используется, например, в третьем сценарии - препод сначала видит только названия (?) лаб, потом выбирает лабу и переходит в режим её просмотра. То есть в момент выбора мы получаем id выбранной лабы и должны вернуть ее контент, по идее (аналогичный метод есть для лабосдач). Возможно, на данный момент избыточно, т.к. teacher_to_labs и так возвращает двумерный массив со всей инфой по лабам (что в свою очередь тоже может быть избыточно, и можно возвращать только пару id - name). В общем, я пока хз немного, что из этого необходимо, мне кажется, надо на фронт посмотреть, а потом уже окончательно решить.
3. Потому что второй цикл удаляет строки из таблицы Лаба-ГД, где лаба не является уникальным ключем.

2021-11-24 09:36 UTC, gri-gri commented
>3. Не очень понимаю, что ты имеешь в виду. На данный момент прога исходит из того, что значения id в каждой табличке - любые числа, идущие в порядке возрастания. Id нового значения в табличке = id последней строки + 1

Я говорю не только про id. Я говорю про то, что впринципе `labs[-1][0]` - плохо, а `labs.get_last_one()["id"]` - хорошо. Но это не надо исправлять, просто на будущее.

>4. list_of_gfs_with_settings - двумерный массив с id ГД, статусами (доступно/недоступно) и дедлайнами. Возможно, стоит это убрать и из основной программы при создании вызывать отдельно new_lab и add_gd_to_lab вместо вызова второй из вызова первой. 5. Массив ГД id, статус (доступно/недоступно), дедлайн.

Не, после разбора я понял, что они из себя представляют. Но на это потребовалось время, поскольку они не интуитивно описаны.

>7.Если мы будем удалять элементы из массива во время его обхода с начала, у нас получатся беды с индексами. Если обходить с конца - всё норм, т.к. индексы меняются только для тех элементов, которые мы уже проверили (кажется). В первом цикле нам надо удалить ровно один элемент, а потом брейкнуть, поэтому без разницы, с какой стороны идти.

Окей

>9. Эмм, нет? Редактирование лабы на данный момент можно сделать только путем удалить лабу - добавить лабу, не уверена, что это наилучший вариант.

А я считаю, что это лучший и единственный вариант. Не вижу в нём ничего плохого.
Про то, что написано далее - это неважно, что будет во фронте, мы ему всё равно и те, и те данные передадим, какая разница, в каком порядке.

2021-11-24 09:38 UTC, gri-gri commented
> На время одного запуска программы они меняются, а большее в текущем варианте и не надо? По поводу полей класса согласна, стоит сделать это хотя бы ради того, чтобы ide перестала ругаться с "method may be static". Другой вопрос, что когда мы заменим двумерные списки на нормальные бд, у нас класс опять останется без полей. Не лучше ли тогда в финальной версии удалить класс и просто оставить все его методы как функции в отдельном файле?

Нет, они не изменяются. Это глобальные переменные, а ты пытаешься их изменять в функции. Либо я уже начал путать языки. Методы можно оставить без класса, но они всё равно объединены одной идеей, концепцией, мегафункцией, поэтому я и предлагал объединить их в один класс.

2021-11-24 19:16 UTC, Martakor1 commented
> Из описания uc 8 и uc 9:
> 
> > 1. Пользователь выбирает из выпадающего списка из групп, в которых он состоит.
> > 2. Выбирает из списка работ нужную
> 
> Не лучше ли сделать выбор не по группе, а по дисциплине?

Ну конечно он должен тыкать на дисциплину. Хотя... Нужна ли тогда вообще эта переключалка. Мне кажется, что лучше всего будет, если вообще никуда не тыкать, а список всех лаб для этого ученика сразу будет высвечиваться. Хотя если лаб будет слишком много, нужно будет долго скролить. Хотя бывает ли лаб в текущем времени больше 10 например?

2021-11-24 21:24 UTC, merged